### infos variables
#server:
#    context-path: /oidcAuth

### infos IDP
redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
 
---
### config vues jsp 

spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
