
### infos IDP

# redirection https://spring-oidc-service.herokuapp.com/login/oauth2/code/azure
  
azure:
  info: Serveur cloud Microsoft Azure AD pour l'authentification des utilisateurs internes à l'organisation
  baseURL: https://login.microsoftonline.com/7efe32b1-bb0f-4849-ae3a-68ee0d8fcf63
  clientId: 5ca4f013-07bd-49a6-bb88-1e3064db1fa1
  clientSecret: -V6A21803mOH9J..5T_DLbQEEpeTuFkXnZ
  issuer: https://login.microsoftonline.com/7efe32b1-bb0f-4849-ae3a-68ee0d8fcf63/v2.0
  iconUrl: https://icons-for-free.com/iconfiles/png/512/logo+microsoft+microsoft+logo+technology+windows+icon-1320167831167856453.png
  
google:
  info: Fournisseur d'identité Google pour le test 
  clientId: 998816284118-pob4qv58q5o866lo8524atghg5thdg4a.apps.googleusercontent.com
  clientSecret: nxr9HWh8l0rV-evLRgP1yFPz
  iconUrl: https://www.google.com/favicon.ico
 
---

### fournisseurs OIDC

# AZURE #
spring:     
  security:
    oauth2:
      client:
        registration:        
          azure:
            client-name: ${azure.info}
            authorization-grant-type: authorization_code
            scope: profile, email, openid
            client-id: ${azure.clientId}
            client-secret: ${azure.clientSecret}
            redirect-uri: ${redirect-uri}
        provider:
          azure:
            authorization-uri: ${azure.baseURL}/oauth2/v2.0/authorize
            token-uri: ${azure.baseURL}/oauth2/v2.0/token
            jwk-set-uri: ${azure.baseURL}/discovery/v2.0/keys
---
# GOOGLE #
spring:     
  security:
    oauth2:
      client:
        registration:                
          google:
            client-name: ${google.info}
            client-id: ${google.clientId}
            client-secret: ${google.clientSecret}

